plugin:
    name: 'uno.pleasewait::lang.plugin.name'
    description: 'uno.pleasewait::lang.plugin.description'
    author: 'Daniel Hernández'
    icon: oc-icon-spinner
    homepage: 'https://github.com/unowebdesign/oc-pleasewait-plugin'
permissions:
    manage_splash_page:
        tab: 'uno.pleasewait::lang.plugin.name'
        label: 'uno.pleasewait::lang.labels.splash_page_permissions'
